# Generated by Django 3.1.7 on 2021-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100)),
                ('ProductDescription', models.CharField(blank=True, max_length=100)),
                ('ProductQuantity', models.IntegerField(blank=True)),
            ],
        ),
    ]
